[package]
name = "action"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy-primitives = { workspace = true }
eyre = { workspace = true }

[lints]
workspace = true