[package]
name = "orchestrator"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "orchestrator"
path = "src/bin/main.rs"

[dependencies]
client = { workspace = true }
balance = { workspace = true }
action = { workspace = true }
binding = { workspace = true }
config = { workspace = true }
withdrawal = { workspace = true }

alloy-provider = { workspace = true }
alloy-primitives = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-network = { workspace = true }
alloy-rpc-types-eth.workspace = true

tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs"] }

eyre = { workspace = true }

serde = { workspace = true }
toml = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }