[package]
name = "orchestrator"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "orchestrator"
path = "src/bin/main.rs"

[dependencies]
# Internal crates
client = { workspace = true }
balance = { workspace = true }

# Alloy
alloy = { workspace = true }
alloy-provider = { workspace = true }
alloy-primitives = { workspace = true }

# Async runtime
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs"] }

# Error handling
eyre = { workspace = true }

# Serialization
serde = { workspace = true }
toml = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }